config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :experiences, only: [:index, :show, :new, :create] do
      resources :bookings, only: [:new, :create]
    end

    resources :bookings, only: [:index, :show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :experience
  belongs_to :user

  validates :date_start, presence: true
  validates :date_end, presence: true
  # validates :final_price, numericality: { greater_than: 0 }
  # validates :status, presence: true
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_one_attached :photo

  belongs_to :user, optional: true

  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  validates :name, presence: true
  validates :stage_name, presence: true
  validates :musical_genre, presence: true
  validates :absurd_requirement, presence: true
  validates :price_per_day, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :experience
  belongs_to :user

  validates :rating, presence: true
  validates :comment, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :reviews, dependent: :destroy

         # Validation
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :show
    end
  end

  def new
    @experience = Experience.find(params[:experience_id])
    @booking = Booking.new
  end

  def create
    @experience = Experience.find(params[:experience_id])
    @booking = Booking.new(booking_params)
    @booking.experience = @experience
    @booking.user = current_user if user_signed_in?
    if @booking.save
      redirect_to experience_path(@experience), notice: "Réservation confirmée !"
    else
      puts @booking.errors.full_messages
      render "experiences/show", status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    @experiences = Experience.all
  end

  def show
    @experience = Experience.find(params[:id])
    @booking = Booking.new
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    if @experience.save
      redirect_to experiences_path, notice: "Expérience créée avec succès !", data: { turbo: false }
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def experience_params
    params.require(:experience).permit(:name, :stage_name, :musical_genre, :absurd_requirement, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @experiences = Experience.all  # Assure-toi que cette ligne récupère les expériences de ta base de données
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@experience, @booking] do |f| %>
  <%= f.input :date_start, placeholder:"Select Start Date..", as: :string, input_html: { data: { controller: "datepicker"} }%>
  <%= f.input :date_end, placeholder:"Select End Date..", as: :string, input_html: { data: { controller: "datepicker" } }  %>
  <%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="container mt-5">
  <h2>Vos réservations:</h2>

  <div class="row">
  <% @bookings.each do |booking| %>
    <div class="col-12 col-md-6 col-lg-4 mb-4 d-flex align-items-stretch">
      <div class="experiences_card d-flex flex-column h-100 w-100">
        <%= link_to booking_path(booking), class: "text-decoration-none text-dark flex-grow-1 d-flex flex-column" do %>
          <% if booking.experience.photo.attached? %>
            <div class="text-center">
              <%= image_tag booking.experience.photo, alt: "Image de l'expérience", class: "img-fluid rounded shadow-lg experiences-img flex-shrink-0" %>
            </div>
          <% else %>
            <p class="text-muted text-center">Aucune photo disponible pour cette expérience.</p>
          <% end %>

          <h4 class="mt-3 flex-grow-1"><%= booking.experience.name %></h4>
          <p class="mt-1 ms-2 text-muted fst-italic text-center flex-shrink-0">🎭 <%= booking.experience.stage_name %></p>

          <div class="experiences_body flex-grow-1 d-flex flex-column justify-content-between">
            <p><i class="fa-solid fa-music"></i> <%= booking.experience.musical_genre %></p>
            <p><i class="fa-solid fa-star"></i> <%= booking.experience.absurd_requirement %></p>
            <p class="price flex-shrink-0"><i class="fa-solid fa-euro-sign"></i> <%= booking.experience.price_per_day%>€/jour</p>
            <p><i class="fa-solid fa-calendar-days"></i> Du: <%= booking.date_start %> Au: <%= booking.date_end %></p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>

</ul>

app/views/bookings/new.html.erb
<div class="container">

  <div class="experience-details mt-4">
          <h3 class="h4">Détails</h3>
          <div class="card mb-3">
            <div class="card-body">
              <p><strong>Nom de scène :</strong> <%= @experience.stage_name %></p>
              <p><strong>Genre musical :</strong> <%= @experience.musical_genre %></p>
              <p><strong>Exigence absurde :</strong> <%= @experience.absurd_requirement %></p>
              <p><strong>Prix par jour :</strong> <%= @experience.price_per_day %> €</p>
            </div>
          </div>
        </div>

  <%= render "form", booking: @booking %>

</div>

app/views/bookings/show.html.erb
<div class="row">
  <% if @booking.present? %>
    <div class="container mt-4">
      <div class="row">
        <div class="show_card">
          <!-- Titre de l'expérience -->
          <h1 class="display-4 text-center"><%= @booking.experience.name %></h1>

          <!-- Section photo de l'expérience -->
          <div class="text-center">
            <% if @booking.experience.photo.attached? %>
              <%= image_tag @booking.experience.photo, alt: "Image de l'expérience"%>
            <% else %>
              <p class="text-muted">Aucune photo disponible pour cette expérience.</p>
            <% end %>
          </div>

          <!-- Détails de l'expérience -->
          <div>
            <h4>Détails</h4>
              <div class="show_card body">
                <p><i class="fa-solid fa-house-chimney"></i> &nbsp<strong>Scène :</strong> <%= @booking.experience.stage_name %></p>
                <p><i class="fa-solid fa-guitar"></i> &nbsp<strong>Genre musical :</strong> <%=  @booking.experience.musical_genre %></p>
                <p><i class="fa-solid fa-people-carry-box"></i> &nbsp<strong>Exigence absurde :</strong> <%=  @booking.experience.absurd_requirement %></p>
                <p><i class="fa-solid fa-money-check-dollar"></i> &nbsp<strong>Prix par jour :</strong> <%=  @booking.experience.price_per_day %> €</p>
              </div>
          </div>

          <div class="show_card resa">
            <h4>Votre réservation: </h4>
            <p><i class="fa-solid fa-calendar-days ms-5"></i> Du: <%= @booking.date_start %> Au: <%= @booking.date_end %></p>
          </div>

          <!-- Section retour à la page d'accueil -->
          <div class="text-center mt-4 mb-5">
            <%= link_to 'Retour à l\'accueil', root_path, class: "btn btn-lg btn-purple rounded-pill px-4 shadow" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/experiences/_form.html.erb
<%= form_with(model: @experience, scope: :experience, url: experiences_path, method: :post, local: true, data: { turbo: false }, html: { multipart: true }) do |form| %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/experiences/index.html.erb
<button class="sticky-add mb-5  btn-purple rounded-pill px-4 shadow ms-4" data-bs-toggle="modal" data-bs-target="#experienceModal" data-turbo="false">
  <i class="fa-solid fa-circle-plus"></i> Ajouter une expérience
</button>

<%= render 'shared/form_modal' %>

<div class="row">
  <% @experiences.each do |experience| %>
    <div class="col-lg-4 mb-4 d-flex align-items-stretch">
      <div class="experiences_card d-flex flex-column ">
        <%= link_to experience_path(experience), class: "text-decoration-none text-dark flex-grow-1 d-flex flex-column" do %>
          <% if experience.photo.attached? %>
            <div class="text-center">
              <%= image_tag experience.photo, alt: "Image de l'expérience", class: "img-fluid rounded shadow-lg flex-shrink-0" %>
            </div>
          <% else %>
            <p class="text-muted text-center">Aucune photo disponible pour cette expérience.</p>
          <% end %>

          <h4 class="mt-3 flex-grow-1"><%= experience.name %></h4>
          <p class="mt-1 ms-2 text-muted fst-italic text-center flex-shrink-0">🎭 <%= experience.stage_name %></p>

          <div class="experiences_body flex-grow-1 d-flex flex-column justify-content-between">
            <p><i class="fa-solid fa-music"></i> <%= experience.musical_genre %></p>
            <p><i class="fa-solid fa-star"></i> <%= experience.absurd_requirement %></p>
            <p class="price flex-shrink-0"><i class="fa-solid fa-euro-sign"></i> <%= experience.price_per_day %>€/jour</p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/experiences/new.html.erb
<div class="container position-relative">

  <div class="position-absolute top-0 end-0 m-3">
    <%= link_to experiences_path, class: "btn-return" do %>
      <i class="fa-solid fa-arrow-left"></i> Retour
    <% end %>
  </div>

  <div class="form-experience">
    <h2>Créer une nouvelle expérience musicale</h2>
    <%= render "experiences/form" %>
  </div>

  <div class="text-center mt-3">
    <%= link_to "Retour aux expériences", experiences_path, class: "btn btn-outline-light rounded-pill" %>
  </div>
</div>

app/views/experiences/show.html.erb
<% if @experience.present? %>
  <div class="container mt-4">
    <div class="row">
      <div class="show_card">
        <!-- Titre de l'expérience -->
        <h2 class="display-4 text-center"><%= @experience.name %></h2>

        <!-- Section photo de l'expérience -->
        <div class="text-center">
          <% if @experience.photo.attached? %>
            <%= image_tag @experience.photo, alt: "Image de l'expérience", class: "img-fluid shadow-lg" %>
          <% else %>
            <p class="text-muted">Aucune photo disponible pour cette expérience.</p>
          <% end %>
        </div>

        <!-- Détails de l'expérience -->
        <div>
          <h4>Détails</h4>
            <div class="show_card body">
              <p><i class="fa-solid fa-house-chimney"></i> &nbsp;<strong>Scène :</strong> <%= @experience.stage_name %></p>
              <p><i class="fa-solid fa-guitar"></i> &nbsp;<strong>Genre musical :</strong> <%= @experience.musical_genre %></p>
              <p><i class="fa-solid fa-people-carry-box"></i> &nbsp;<strong>Exigence absurde :</strong> <%= @experience.absurd_requirement %></p>
              <p><i class="fa-solid fa-money-check-dollar"></i> &nbsp;<strong>Prix par jour :</strong> <%= @experience.price_per_day %> €</p>
            </div>
        </div>

        <!-- Boutons de navigation -->
        <div class="text-center mb-5 mt-5">
          <%= link_to 'Retour à l\'accueil', root_path, class: "btn btn-lg btn-purple rounded-pill px-4 shadow" %>


          <!-- Bouton pour ouvrir la modal de réservation -->
          <button class="btn btn-lg btn-purple rounded-pill px-4 shadow ms-4" data-bs-toggle="modal" data-bs-target="#experienceBookingModal" data-turbo="false">
            <i class="fa-solid fa-calendar-plus"></i> Réserver cette expérience
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal de réservation -->
  <div class="modal fade" id="experienceBookingModal" tabindex="-1" aria-labelledby="bookingModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <div class="modal-header">
          <h2 id="modalTitle" class="modal-title">Réserver cette expérience</h2>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Fermer"></button>
        </div>

        <div class="modal-body">
          <div class="custom-experience-card">
            <div class="card-header">
              <h4 class="neon-text"><%= @experience.name %></h4>
            </div>

            <div class="card-body">
              <p><i class="fa-solid fa-microphone-lines"></i> <strong>:</strong> <%= @experience.stage_name %></p>
              <p><i class="fa-solid fa-music"></i> <strong> :</strong> <%= @experience.musical_genre %></p>
              <p><i class="fa-solid fa-star"></i> <strong> :</strong> <%= @experience.absurd_requirement %></p>
              <p><i class="fa-solid fa-euro-sign"></i> <strong> :</strong> <%= @experience.price_per_day %> €</p>
            </div>
          </div>

          <div class="text-center">
            <h3 class="h5 text-purple mt-3 mb-3">📅 Sélectionnez vos dates</h3>
          </div>

          <%= simple_form_for [@experience, @booking || Booking.new], html: { class: "custom-booking-form" } do |f| %>
            <div class="row">

              <div class="col-md-6">
                <div class="input-wrapper">
                  <i class="fa-solid fa-calendar-day neon-icon"></i>
                  <%= f.input :date_start, as: :string, input_html: { data: { controller: "datepicker" }, class: "form-control neon-input", placeholder: "📅 Date de début" }, label: false %>
                </div>
              </div>

              <div class="col-md-6">
                <div class="input-wrapper">
                  <i class="fa-solid fa-calendar-check neon-icon"></i>
                  <%= f.input :date_end, as: :string, input_html: { data: { controller: "datepicker" }, class: "form-control neon-input", placeholder: "📅 Date de fin" }, label: false %>
                </div>
              </div>
            </div>

            <div class="text-center mt-4">
              <%= f.submit "Confirmer la réservation", id: "btn-booking", class: "btn-neon" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% else %>
  <div class="container mt-5">
    <div class="row">
      <div class="col">
        <p class="text-center">Aucune expérience trouvée.</p>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBandB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_frame_tag "turbo-frame", data: { turbo: "false" } %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <div class="container mt-3">
      <% if notice.present? %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
    </div>

    <main class="container my-4">
      <%= yield %>
    </main>

    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container back">
<div class="container mt-5">
 <div class="banner position-relative d-flex align-items-center text-white text-center"
       style="background: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)),
              url('https://images.unsplash.com/photo-1566808907623-51b8fc382454?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');
              background-size: cover; background-position: center; height: 60vh;">

    <div class="containe main-home">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h1 class="display-3 fw-bold">AirBandB – L'expérience musicale sans limite !</h1>
          <p class="fs-4 fst-italic">Des concerts ? Non. Des expériences inoubliables !</p>

          <div class="mt-4">
            <button class="btn btn-lg btn-purple rounded-pill px-4 shadow" data-bs-toggle="modal" data-bs-target="#experienceModal">
              Proposer une expérience 🎤
            </button>

            <%= link_to "Explorer les expériences 🤩", experiences_path,
                        class: "btn btn-lg btn-purple rounded-pill px-4 ms-2 shadow" %>
          </div>
        </div>
      </div>
    </div>
  </div>

<%= render "shared/form_modal" %>

  <div class="text-center mt-5">
    <h2 class="fw-bold mt-3">🔥 Déjà <%= Experience.count %> expériences musicales délirantes enregistrées ! 🔥</h2>
  </div>

<div class="row">
  <% @experiences.order("RANDOM()").first(3).each do |experience| %>
    <div class="col-12 col-md-6 col-lg-4 mb-4 d-flex align-items-stretch">
      <div class="experiences_card d-flex flex-column h-100 w-100">
        <%= link_to experience_path(experience), class: "text-decoration-none text-dark flex-grow-1 d-flex flex-column" do %>
          <% if experience.photo.attached? %>
            <div class="text-center">
              <%= image_tag experience.photo, alt: "Image de l'expérience", class: "img-fluid rounded shadow-lg experiences-img flex-shrink-0" %>
            </div>
          <% else %>
            <p class="text-muted text-center">Aucune photo disponible pour cette expérience.</p>
          <% end %>

          <h4 class="mt-3 flex-grow-1"><%= experience.name %></h4>
          <p class="mt-1 ms-2 text-muted fst-italic text-center flex-shrink-0">🎭 <%= experience.stage_name %></p>

          <div class="experiences_body flex-grow-1 d-flex flex-column justify-content-between">
            <p><i class="fa-solid fa-music"></i> <%= experience.musical_genre %></p>
            <p><i class="fa-solid fa-star"></i> <%= experience.absurd_requirement %></p>
            <p class="price flex-shrink-0"><i class="fa-solid fa-euro-sign"></i> <%= experience.price_per_day %>€/jour</p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>
<div class="text-center mt-5">
  <h2 class="fw-bold text-uppercase mt-5">🎲 Pas inspiré ? Tire au sort une expérience musicale !</h2>
  <%= link_to "🎲 Découvrir une expérience aléatoire", experience_path(Experience.order("RANDOM()").first),
              class: "btn btn-warning btn-lg btn-purple btn-purple-dark mt-3 rounded-pill shadow", id: "hel"%>
</div>
</div>
<footer class="d-flex flex-column justify-content-center align-items-center text-center py-4 mt-5 bg-dark text-light">
  <p class="m-0">© <%= Time.now.year %> AirBandB. Tous droits réservés.</p>
  <p class="m-0 fst-italic">“Trouvez l’expérience musicale de vos rêves… ou de vos cauchemars.”</p>
</footer>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <p class="mt-3">Le lieu idéal pour trouver des expériences musicales qui te correspondent ! <i class="fa-solid fa-music"></i></p>
  </div>

app/views/shared/_form_modal.html.erb
<div class="modal fade" id="experienceModal" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h2 id="modalTitle" class="modal-title">Créer une nouvelle expérience musicale</h2>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
      </div>

      <div class="modal-body">
        <%= form_with(model: @experience, scope: :experience, url: experiences_path, method: :post, local: true, data: { turbo: false }, html: { multipart: true }) do |f| %>
          <div class="mb-3">
            <%= f.label :name, "Nom de l'expérience", class: "form-label" %>
            <%= f.text_field :name, class: "form-control", placeholder: "Ex: Jazz & Chill à Paris" %>
          </div>

          <div class="mb-3">
            <%= f.label :stage_name, "Scène", class: "form-label" %>
            <%= f.text_field :stage_name, class: "form-control", placeholder: "Ex: Catacombes" %>
          </div>

          <div class="mb-3">
            <%= f.label :musical_genre, "Genre musical", class: "form-label" %>
            <%= f.text_field :musical_genre, class: "form-control", placeholder: "Ex: Rock, Jazz, Electro..." %>
          </div>

          <div class="mb-3">
            <%= f.label :absurd_requirement, "Exigence absurde", class: "form-label" %>
            <%= f.text_field :absurd_requirement, class: "form-control", placeholder: "Ex: Un lama en coulisses 🦙" %>
          </div>

          <div class="mb-3">
            <%= f.label :price_per_day, "Tarif par jour (€)", class: "form-label" %>
            <%= f.number_field :price_per_day, class: "form-control", placeholder: "Ex: 500" %>
          </div>

          <div class="mb-3">
            <%= f.label :photo, "Photo de l'expérience", class: "form-label" %>
            <label class="file-upload">
              <i class="fa-solid fa-camera-retro"></i> Ajouter une photo
              <%= f.file_field :photo, class: "d-none" %>
            </label>
          </div>

          <div class="text-center mt-4">
            <%= f.button "Créer l'expérience", id: "btn-custom", class: "btn-submit" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_modal_booking.html.erb
<div class="modal fade" id="experienceBookingModal" tabindex="-1" aria-labelledby="bookingModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <h2 id="modalTitle" class="modal-title">Réserver cette expérience </h2>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Fermer"></button>
      </div>


      <div class="modal-body">
        <div class="custom-experience-card">
          <div class="card-header">
            <h4 class="neon-text"><%= @experience.name %></h4>
          </div>

          <div class="card-body">
            <p><i class="fa-solid fa-microphone-lines"></i> :<strong>:</strong> <%= @experience.stage_name %></p>
            <p><i class="fa-solid fa-music"></i> <strong> :</strong> <%= @experience.musical_genre %></p>
            <p><i class="fa-solid fa-star"></i> <strong> :</strong> <%= @experience.absurd_requirement %></p>
            <p><i class="fa-solid fa-euro-sign"></i> <strong> :</strong> <%= @experience.price_per_day %> €</p>
          </div>
</div>


        <div class="text-center">
          <h3 class="h5 text-purple >📅 Sélectionnez vos dates</h3>
        </div>

        <%= simple_form_for [@experience, @booking || Booking.new], html: { class: "custom-booking-form" } do |f| %>
          <div class="row">

            <div class="col-md-6">
              <div class="input-wrapper">
                <i class="fa-solid fa-calendar-day neon-icon"></i>
                <%= f.input :date_start, as: :string, input_html: { data: { controller: "datepicker" }, class: "form-control neon-input", placeholder: "📅 Date de début" },
                label: false %>
              </div>
              </div>

            <div class="col-md-6">
              <div class="input-wrapper">
                <i class="fa-solid fa-calendar-check neon-icon"></i>
                <%= f.input :date_end, as: :string,
                input_html: { data: { controller: "datepicker" }, class: "form-control neon-input", placeholder: "📅 Date de fin" },
                label: false %>
              </div>
            </div>
            </div>


            <div class="text-center mt-4">
                <%= f.submit "Confirmer la réservation", id: "btn-booking", class: "btn-neon" %>
            </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <div class="navbar-title d-flex align-items-center justify-content-start">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://as1.ftcdn.net/v2/jpg/03/11/40/32/1000_F_311403223_PqZgUJBzDitoQu2GJ86wHbNCJxpXK7FZ.jpg", style: "width: 60px; height: auto; border-radius: 15px;" %>
      <% end %>
      <h5 class="mt-2">AirbandB</h5>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Experiences", experiences_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path ,  class: "nav-link" %>
          </li>

          <%# dropdown with user login_un & log_out %>
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <%= image_tag current_user.avatar_url.presence || "https://media.istockphoto.com/id/1431567498/fr/vectoriel/illustration-vectorielle-de-notes-de-musique-sur-fond-blanc.jpg?s=612x612&w=0&k=20&c=BlXbPeaCz3PEle5hXy6ndnVw_4OKunNSUInE-QbDYg4=",
                class: "avatar dropdown-toggle",
                id: "navbarDropdown",
                data: { bs_toggle: "dropdown", bs_auto_close: "outside" },
                'aria-haspopup': true,
                'aria-expanded': false
              %>

              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <span class="dropdown-item-text fw-bold">
                  👤 <%= current_user.name || "Utilisateur" %>
                </span>

                <%= link_to "Profil", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Mes réservations", bookings_path, class: "dropdown-item" %>

                <div class="dropdown-divider"></div>

                <%= link_to "Déconnexion", destroy_user_session_path, class: "dropdown-item text-danger", data: { turbo_method: :delete } %>
              </div>
            <% else %>
              <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
            <% end %>
          </li>

          <% if !user_signed_in? %>
            <li class="nav-item">
              <%= link_to "S'inscrire", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>